exports.run = (bot, message, args) => {

  let FunEmbed = new Discord.RichEmbed()
  .setTitle("FUN COMMANDS")
  .addField("cry", "now you can cry")
  .addField("okay", "okay GIF")
  .addField("silence", "when you just want someone to stfu")
  .addField("r@pe", "rape someone")
  .addField("hug(s)", "hug someone")
  .addField("roll", "roll the dice and test your luck")
  .addField("roulette", "spin the barrel and test your luck")
  .addField("revive", "try and revive the chat")
  .addField("bonus_duck", "???")
  .addField("km5", "kys, silently")
  .addField("insult", "insult someone")
  .addField("facepalm", "facepalm GIF")
  .addField("shrug", "¯\\_(ツ)_/¯")
  .addField("lenny", "you know what to do...( ͡° ͜ʖ ͡°)")
  .addField("why", "why not?")
  .addField("random", "random GIF")
  .addField("chat", "tag a random person to annoy them or to chat")
  .addField("lennyception", "( ͡° ͜ʖ ͡°) same as this but more")
  .addField("wow", "wow GIF (btw I made this gif)")
  .addField("say", "try it!")
  .setColor(0x0FFF255)
  .setThumbnail(bot.avatarURL)
  message.author.sendEmbed(FunEmbed)
  let adminembed = new Discord.RichEmbed()
  .setTitle("ADMIN COMMANDS")
  .addField("delete", "deletes a specified amount of messages.")
  .addField("mute","mutes a member.")
  .addField("unmute", "unmutes a muted person.")
  .addField("invitepls", "generates an invite for the channel you are on (code).")
  .addField("invitelink", "generates an invite link. Note: this does not work with anti-ad bots...use *invitepls for this. :)")
  .addField("kick", "kicks a member.")
  .addField("warn", "warns a member.")
  .addField("status", "the bot's current status.")
  .addField("sayd", "same as *say but now it deletes the command.")
  .setColor(0x0FFF255)
  .setThumbnail(message.author.avatarURL)
  message.author.sendEmbed(adminembed)
  message.channel.sendMessage("Check your DM's")
  
  }